
export const data = [
    {
        year: 1940,
        "detail": [
            { month: 0, expense: 35 },
            { month: 1, expense: 65 },
            { month: 2, expense: 100 },
            { month: 3, expense: 45 },
            { month: 4, expense: 85 },
            { month: 5, expense: 28 },
            { month: 6, expense: 15 },
            { month: 7, expense: 65 },
            { month: 8, expense: 22 },
            { month: 9, expense: 65 },
            { month: 10, expense: 25 },
            { month: 11, expense: 20 },
        ],
    },
    {
        year: 1941,
        "detail": [
            { month: 0, expense: 40 },
            { month: 1, expense: 70 },
            { month: 2, expense: 105 },
            { month: 3, expense: 50 },
            { month: 4, expense: 90 },
            { month: 5, expense: 32 },
            { month: 6, expense: 20 },
            { month: 7, expense: 70 },
            { month: 8, expense: 28 },
            { month: 9, expense: 70 },
            { month: 10, expense: 32 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1942,
        "detail": [
            { month: 0, expense: 45 },
            { month: 1, expense: 75 },
            { month: 2, expense: 110 },
            { month: 3, expense: 55 },
            { month: 4, expense: 95 },
            { month: 5, expense: 35 },
            { month: 6, expense: 24 },
            { month: 7, expense: 75 },
            { month: 8, expense: 30 },
            { month: 9, expense: 75 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1943,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 115 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 80 },
            { month: 8, expense: 32 },
            { month: 9, expense: 80 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1944,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 110 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 85 },
            { month: 8, expense: 35 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1945,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 95 },
            { month: 2, expense: 100 },
            { month: 3, expense: 75 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 35 },
            { month: 7, expense: 90 },
            { month: 8, expense: 40 },
            { month: 9, expense: 88 },
            { month: 10, expense: 42 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1946,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 105 },
            { month: 3, expense: 72 },
            { month: 4, expense: 115 },
            { month: 5, expense: 48 },
            { month: 6, expense: 30 },
            { month: 7, expense: 88 },
            { month: 8, expense: 38 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 33 },
        ],
    },
    {
        year: 1947,
        "detail": [
            { month: 0, expense: 48 },
            { month: 1, expense: 78 },
            { month: 2, expense: 115 },
            { month: 3, expense: 62 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 24 },
            { month: 7, expense: 82 },
            { month: 8, expense: 28 },
            { month: 9, expense: 75 },
            { month: 10, expense: 30 },
            { month: 11, expense: 25 },
        ],
    },
    {
        year: 1948,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 85 },
            { month: 2, expense: 120 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 80 },
            { month: 8, expense: 35 },
            { month: 9, expense: 78 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1949,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 92 },
            { month: 2, expense: 110 },
            { month: 3, expense: 70 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 25 },
            { month: 7, expense: 85 },
            { month: 8, expense: 30 },
            { month: 9, expense: 82 },
            { month: 10, expense: 36 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1950,
        "detail": [
            { month: 0, expense: 40 },
            { month: 1, expense: 70 },
            { month: 2, expense: 105 },
            { month: 3, expense: 50 },
            { month: 4, expense: 90 },
            { month: 5, expense: 32 },
            { month: 6, expense: 18 },
            { month: 7, expense: 70 },
            { month: 8, expense: 25 },
            { month: 9, expense: 70 },
            { month: 10, expense: 28 },
            { month: 11, expense: 22 },
        ],
    },
    {
        year: 1951,
        "detail": [
            { month: 0, expense: 45 },
            { month: 1, expense: 75 },
            { month: 2, expense: 110 },
            { month: 3, expense: 55 },
            { month: 4, expense: 95 },
            { month: 5, expense: 35 },
            { month: 6, expense: 24 },
            { month: 7, expense: 75 },
            { month: 8, expense: 30 },
            { month: 9, expense: 75 },
            { month: 10, expense: 32 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1952,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 115 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 80 },
            { month: 8, expense: 32 },
            { month: 9, expense: 80 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1953,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 110 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 85 },
            { month: 8, expense: 35 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1954,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 95 },
            { month: 2, expense: 100 },
            { month: 3, expense: 75 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 35 },
            { month: 7, expense: 90 },
            { month: 8, expense: 40 },
            { month: 9, expense: 88 },
            { month: 10, expense: 42 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1955,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 105 },
            { month: 3, expense: 72 },
            { month: 4, expense: 115 },
            { month: 5, expense: 48 },
            { month: 6, expense: 30 },
            { month: 7, expense: 88 },
            { month: 8, expense: 38 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 33 },
        ],
    },
    {
        year: 1956,
        "detail": [
            { month: 0, expense: 48 },
            { month: 1, expense: 78 },
            { month: 2, expense: 115 },
            { month: 3, expense: 62 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 24 },
            { month: 7, expense: 82 },
            { month: 8, expense: 28 },
            { month: 9, expense: 75 },
            { month: 10, expense: 30 },
            { month: 11, expense: 25 },
        ],
    },
    {
        year: 1957,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 85 },
            { month: 2, expense: 120 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 80 },
            { month: 8, expense: 35 },
            { month: 9, expense: 78 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1958,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 92 },
            { month: 2, expense: 110 },
            { month: 3, expense: 70 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 25 },
            { month: 7, expense: 85 },
            { month: 8, expense: 30 },
            { month: 9, expense: 82 },
            { month: 10, expense: 36 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1959,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 118 },
            { month: 3, expense: 62 },
            { month: 4, expense: 105 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 90 },
            { month: 8, expense: 32 },
            { month: 9, expense: 78 },
            { month: 10, expense: 38 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1960,
        "detail": [
            { month: 0, expense: 45 },
            { month: 1, expense: 75 },
            { month: 2, expense: 110 },
            { month: 3, expense: 55 },
            { month: 4, expense: 95 },
            { month: 5, expense: 35 },
            { month: 6, expense: 20 },
            { month: 7, expense: 75 },
            { month: 8, expense: 28 },
            { month: 9, expense: 75 },
            { month: 10, expense: 30 },
            { month: 11, expense: 25 },
        ],
    },
    {
        year: 1961,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 115 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 80 },
            { month: 8, expense: 32 },
            { month: 9, expense: 80 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1962,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 110 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 85 },
            { month: 8, expense: 35 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1963,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 95 },
            { month: 2, expense: 100 },
            { month: 3, expense: 75 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 35 },
            { month: 7, expense: 90 },
            { month: 8, expense: 40 },
            { month: 9, expense: 88 },
            { month: 10, expense: 42 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1964,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 105 },
            { month: 3, expense: 72 },
            { month: 4, expense: 115 },
            { month: 5, expense: 48 },
            { month: 6, expense: 30 },
            { month: 7, expense: 88 },
            { month: 8, expense: 38 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 33 },
        ],
    },
    {
        year: 1965,
        "detail": [
            { month: 0, expense: 48 },
            { month: 1, expense: 78 },
            { month: 2, expense: 115 },
            { month: 3, expense: 62 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 24 },
            { month: 7, expense: 82 },
            { month: 8, expense: 28 },
            { month: 9, expense: 75 },
            { month: 10, expense: 30 },
            { month: 11, expense: 25 },
        ],
    },
    {
        year: 1966,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 85 },
            { month: 2, expense: 120 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 80 },
            { month: 8, expense: 35 },
            { month: 9, expense: 78 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1967,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 92 },
            { month: 2, expense: 110 },
            { month: 3, expense: 70 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 25 },
            { month: 7, expense: 85 },
            { month: 8, expense: 30 },
            { month: 9, expense: 82 },
            { month: 10, expense: 36 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1968,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 118 },
            { month: 3, expense: 62 },
            { month: 4, expense: 105 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 90 },
            { month: 8, expense: 32 },
            { month: 9, expense: 78 },
            { month: 10, expense: 38 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1969,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 115 },
            { month: 3, expense: 70 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 32 },
            { month: 7, expense: 95 },
            { month: 8, expense: 38 },
            { month: 9, expense: 85 },
            { month: 10, expense: 40 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1970,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 120 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 25 },
            { month: 7, expense: 80 },
            { month: 8, expense: 30 },
            { month: 9, expense: 80 },
            { month: 10, expense: 32 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1971,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 90 },
            { month: 2, expense: 110 },
            { month: 3, expense: 70 },
            { month: 4, expense: 120 },
            { month: 5, expense: 50 },
            { month: 6, expense: 30 },
            { month: 7, expense: 85 },
            { month: 8, expense: 35 },
            { month: 9, expense: 85 },
            { month: 10, expense: 40 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1972,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 95 },
            { month: 2, expense: 100 },
            { month: 3, expense: 75 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 35 },
            { month: 7, expense: 90 },
            { month: 8, expense: 40 },
            { month: 9, expense: 88 },
            { month: 10, expense: 42 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1973,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 105 },
            { month: 3, expense: 72 },
            { month: 4, expense: 115 },
            { month: 5, expense: 48 },
            { month: 6, expense: 30 },
            { month: 7, expense: 88 },
            { month: 8, expense: 38 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 33 },
        ],
    },
    {
        year: 1974,
        "detail": [
            { month: 0, expense: 58 },
            { month: 1, expense: 92 },
            { month: 2, expense: 110 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 28 },
            { month: 7, expense: 85 },
            { month: 8, expense: 32 },
            { month: 9, expense: 80 },
            { month: 10, expense: 38 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1975,
        "detail": [
            { month: 0, expense: 48 },
            { month: 1, expense: 78 },
            { month: 2, expense: 115 },
            { month: 3, expense: 62 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 24 },
            { month: 7, expense: 82 },
            { month: 8, expense: 28 },
            { month: 9, expense: 75 },
            { month: 10, expense: 30 },
            { month: 11, expense: 25 },
        ],
    },
    {
        year: 1976,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 85 },
            { month: 2, expense: 120 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 80 },
            { month: 8, expense: 35 },
            { month: 9, expense: 78 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 1977,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 92 },
            { month: 2, expense: 110 },
            { month: 3, expense: 70 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 25 },
            { month: 7, expense: 85 },
            { month: 8, expense: 30 },
            { month: 9, expense: 82 },
            { month: 10, expense: 36 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1978,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 118 },
            { month: 3, expense: 62 },
            { month: 4, expense: 105 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 90 },
            { month: 8, expense: 32 },
            { month: 9, expense: 78 },
            { month: 10, expense: 38 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1979,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 115 },
            { month: 3, expense: 70 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 32 },
            { month: 7, expense: 95 },
            { month: 8, expense: 38 },
            { month: 9, expense: 85 },
            { month: 10, expense: 40 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1980,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 380 },
            { month: 2, expense: 120 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 25 },
            { month: 7, expense: 80 },
            { month: 8, expense: 30 },
            { month: 9, expense: 80 },
            { month: 10, expense: 32 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1981,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 400 },
            { month: 2, expense: 130 },
            { month: 3, expense: 65 },
            { month: 4, expense: 110 },
            { month: 5, expense: 36 },
            { month: 6, expense: 28 },
            { month: 7, expense: 92 },
            { month: 8, expense: 34 },
            { month: 9, expense: 92 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1982,
        "detail": [
            { month: 0, expense: 40 },
            { month: 1, expense: 67 },
            { month: 2, expense: 89 },
            { month: 3, expense: 23 },
            { month: 4, expense: 54 },
            { month: 5, expense: 72 },
            { month: 6, expense: 38 },
            { month: 7, expense: 19 },
            { month: 8, expense: 22 },
            { month: 9, expense: 11 },
            { month: 10, expense: 36 },
            { month: 11, expense: 98 },
        ],
    },
    {
        year: 1983,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 400 },
            { month: 2, expense: 130 },
            { month: 3, expense: 65 },
            { month: 4, expense: 110 },
            { month: 5, expense: 36 },
            { month: 6, expense: 28 },
            { month: 7, expense: 92 },
            { month: 8, expense: 34 },
            { month: 9, expense: 92 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 1984,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 380 },
            { month: 2, expense: 120 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 25 },
            { month: 7, expense: 80 },
            { month: 8, expense: 30 },
            { month: 9, expense: 80 },
            { month: 10, expense: 32 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1985,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 380 },
            { month: 2, expense: 120 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 25 },
            { month: 7, expense: 80 },
            { month: 8, expense: 30 },
            { month: 9, expense: 80 },
            { month: 10, expense: 32 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 1986,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 400 },
            { month: 2, expense: 130 },
            { month: 3, expense: 55 },
            { month: 4, expense: 110 },
            { month: 5, expense: 36 },
            { month: 6, expense: 28 },
            { month: 7, expense: 92 },
            { month: 8, expense: 34 },
            { month: 9, expense: 92 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ]
    },
    {
        year: 1997,
        "detail": [
            { month: 0, expense: 70 },
            { month: 1, expense: 420 },
            { month: 2, expense: 140 },
            { month: 3, expense: 50 },
            { month: 4, expense: 105 },
            { month: 5, expense: 38 },
            { month: 6, expense: 78 },
            { month: 7, expense: 36 },
            { month: 8, expense: 82 },
            { month: 9, expense: 97 },
            { month: 10, expense: 28 },
            { month: 11, expense: 39 },
        ]
    },
    {
        year: 1989,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 400 },
            { month: 2, expense: 130 },
            { month: 3, expense: 55 },
            { month: 4, expense: 110 },
            { month: 5, expense: 36 },
            { month: 6, expense: 28 },
            { month: 7, expense: 92 },
            { month: 8, expense: 34 },
            { month: 9, expense: 92 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ]
    },
    {
        year: 1989,
        "detail": [
            { month: 0, expense: 0 },
            { month: 1, expense: 0 },
            { month: 2, expense: 0 },
            { month: 3, expense: 0 },
            { month: 4, expense: 0 },
            { month: 5, expense: 0 },
            { month: 6, expense: 0 },
            { month: 7, expense: 0 },
            { month: 8, expense: 0 },
            { month: 9, expense: 0 },
            { month: 10, expense: 0 },
            { month: 11, expense: 0 },
        ],
    },
    {
        year: 1990,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 400 },
            { month: 2, expense: 130 },
            { month: 3, expense: 55 },
            { month: 4, expense: 110 },
            { month: 5, expense: 36 },
            { month: 6, expense: 28 },
            { month: 7, expense: 92 },
            { month: 8, expense: 34 },
            { month: 9, expense: 92 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ]
    },
    {
        year: 1991,
        "detail": [
            { month: 0, expense: 70 },
            { month: 1, expense: 420 },
            { month: 2, expense: 140 },
            { month: 3, expense: 50 },
            { month: 4, expense: 105 },
            { month: 5, expense: 38 },
            { month: 6, expense: 78 },
            { month: 7, expense: 36 },
            { month: 8, expense: 82 },
            { month: 9, expense: 97 },
            { month: 10, expense: 28 },
            { month: 11, expense: 39 },
        ]
    },
    {
        year: 1992,
        "detail": [
            { month: 0, expense: 180 },
            { month: 1, expense: 210 },
            { month: 2, expense: 135 },
            { month: 3, expense: 160 },
            { month: 4, expense: 130 },
            { month: 5, expense: 260 },
            { month: 6, expense: 165 },
            { month: 7, expense: 140 },
            { month: 8, expense: 190 },
            { month: 9, expense: 210 },
            { month: 10, expense: 145 },
            { month: 11, expense: 120 },
        ]
    },
    {
        year: 1993,
        "detail": [
            { month: 0, expense: 200 },
            { month: 1, expense: 230 },
            { month: 2, expense: 155 },
            { month: 3, expense: 180 },
            { month: 4, expense: 150 },
            { month: 5, expense: 280 },
            { month: 6, expense: 185 },
            { month: 7, expense: 160 },
            { month: 8, expense: 210 },
            { month: 9, expense: 230 },
            { month: 10, expense: 165 },
            { month: 11, expense: 140 },
        ]
    },
    {
        year: 1994,
        "detail": [
            { month: 0, expense: 120 },
            { month: 1, expense: 150 },
            { month: 2, expense: 75 },
            { month: 3, expense: 100 },
            { month: 4, expense: 70 },
            { month: 5, expense: 200 },
            { month: 6, expense: 105 },
            { month: 7, expense: 80 },
            { month: 8, expense: 130 },
            { month: 9, expense: 150 },
            { month: 10, expense: 85 },
            { month: 11, expense: 60 },
        ]
    },
    {
        year: 1995,
        "detail": [
            { month: 0, expense: 140 },
            { month: 1, expense: 170 },
            { month: 2, expense: 95 },
            { month: 3, expense: 120 },
            { month: 4, expense: 90 },
            { month: 5, expense: 220 },
            { month: 6, expense: 125 },
            { month: 7, expense: 100 },
            { month: 8, expense: 150 },
            { month: 9, expense: 170 },
            { month: 10, expense: 105 },
            { month: 11, expense: 80 },
        ]
    },
    {
        year: 1994,
        "detail": [
            { month: 0, expense: 160 },
            { month: 1, expense: 190 },
            { month: 2, expense: 115 },
            { month: 3, expense: 140 },
            { month: 4, expense: 110 },
            { month: 5, expense: 240 },
            { month: 6, expense: 145 },
            { month: 7, expense: 120 },
            { month: 8, expense: 170 },
            { month: 9, expense: 190 },
            { month: 10, expense: 125 },
            { month: 11, expense: 100 },
        ]
    },
    {
        year: 1995,
        "detail": [
            { month: 0, expense: 180 },
            { month: 1, expense: 210 },
            { month: 2, expense: 135 },
            { month: 3, expense: 160 },
            { month: 4, expense: 130 },
            { month: 5, expense: 260 },
            { month: 6, expense: 165 },
            { month: 7, expense: 140 },
            { month: 8, expense: 190 },
            { month: 9, expense: 210 },
            { month: 10, expense: 145 },
            { month: 11, expense: 120 },
        ]
    },
    {
        year: 1996,
        "detail": [
            { month: 0, expense: 200 },
            { month: 1, expense: 230 },
            { month: 2, expense: 155 },
            { month: 3, expense: 180 },
            { month: 4, expense: 150 },
            { month: 5, expense: 280 },
            { month: 6, expense: 185 },
            { month: 7, expense: 160 },
            { month: 8, expense: 210 },
            { month: 9, expense: 230 },
            { month: 10, expense: 165 },
            { month: 11, expense: 140 },
        ]
    },
    {
        year: 1997,
        "detail": [
            { month: 0, expense: 220 },
            { month: 1, expense: 250 },
            { month: 2, expense: 175 },
            { month: 3, expense: 200 },
            { month: 4, expense: 170 },
            { month: 5, expense: 300 },
            { month: 6, expense: 205 },
            { month: 7, expense: 180 },
            { month: 8, expense: 230 },
            { month: 9, expense: 250 },
            { month: 10, expense: 185 },
            { month: 11, expense: 160 },
        ]
    },
    {
        year: 1998,
        "detail": [
            { month: 0, expense: 240 },
            { month: 1, expense: 270 },
            { month: 2, expense: 195 },
            { month: 3, expense: 220 },
            { month: 4, expense: 190 },
            { month: 5, expense: 320 },
            { month: 6, expense: 225 },
            { month: 7, expense: 200 },
            { month: 8, expense: 250 },
            { month: 9, expense: 270 },
            { month: 10, expense: 205 },
            { month: 11, expense: 180 },
        ]
    },
    {
        year: 1999,
        "detail": [
            { month: 0, expense: 15 },
            { month: 1, expense: 10 },
            { month: 2, expense: 80 },
            { month: 3, expense: 75 },
            { month: 4, expense: 45 },
            { month: 5, expense: 20 },
            { month: 6, expense: 10 },
            { month: 7, expense: 110 },
            { month: 8, expense: 120 },
            { month: 9, expense: 80 },
            { month: 10, expense: 90 },
            { month: 11, expense: 18 },
        ]
    },
    {
        year: 2000,
        "detail": [
            { month: 0, expense: 100 },
            { month: 1, expense: 110 },
            { month: 2, expense: 120 },
            { month: 3, expense: 130 },
            { month: 4, expense: 140 },
            { month: 5, expense: 150 },
            { month: 6, expense: 160 },
            { month: 7, expense: 170 },
            { month: 8, expense: 180 },
            { month: 9, expense: 190 },
            { month: 10, expense: 200 },
            { month: 11, expense: 210 },
        ]
    },
    {
        year: 2001,
        "detail": [
            { month: 0, expense: 15 },
            { month: 1, expense: 10 },
            { month: 2, expense: 80 },
            { month: 3, expense: 75 },
            { month: 4, expense: 45 },
            { month: 5, expense: 20 },
            { month: 6, expense: 10 },
            { month: 7, expense: 110 },
            { month: 8, expense: 120 },
            { month: 9, expense: 80 },
            { month: 10, expense: 90 },
            { month: 11, expense: 18 },
        ]
    },
    {
        year: 2002,
        "detail": [
            { month: 0, expense: 10 },
            { month: 1, expense: 380 },
            { month: 2, expense: 120 },
            { month: 3, expense: 45 },
            { month: 4, expense: 98 },
            { month: 5, expense: 34 },
            { month: 6, expense: 18 },
            { month: 7, expense: 22 },
            { month: 8, expense: 65 },
            { month: 9, expense: 13 },
            { month: 10, expense: 19 },
            { month: 11, expense: 49 },
        ]
    },
    {
        year: 2003,
        "detail": [
            { month: 0, expense: 98 },
            { month: 1, expense: 23 },
            { month: 2, expense: 54 },
            { month: 3, expense: 93 },
            { month: 4, expense: 27 },
            { month: 5, expense: 64 },
            { month: 6, expense: 94 },
            { month: 7, expense: 23 },
            { month: 8, expense: 43 },
            { month: 9, expense: 87 },
            { month: 10, expense: 35 },
            { month: 11, expense: 78 },
        ]
    },
    {
        year: 2004,
        "detail": [
            { month: 0, expense: 94 },
            { month: 1, expense: 33 },
            { month: 2, expense: 20 },
            { month: 3, expense: 52 },
            { month: 4, expense: 82 },
            { month: 5, expense: 94 },
            { month: 6, expense: 96 },
            { month: 7, expense: 34 },
            { month: 8, expense: 87 },
            { month: 9, expense: 23 },
            { month: 10, expense: 19 },
            { month: 11, expense: 23 },
        ]
    },
    {
        year: 2005,
        "detail": [
            { month: 0, expense: 93 },
            { month: 1, expense: 10 },
            { month: 2, expense: 50 },
            { month: 3, expense: 25 },
            { month: 4, expense: 10 },
            { month: 5, expense: 220 },
            { month: 6, expense: 93 },
            { month: 7, expense: 112 },
            { month: 8, expense: 56 },
            { month: 9, expense: 23 },
            { month: 10, expense: 34 },
            { month: 11, expense: 27 },
        ]
    },
    {
        year: 2006,
        "detail": [
            { month: 0, expense: 120 },
            { month: 1, expense: 80 },
            { month: 2, expense: 45 },
            { month: 3, expense: 60 },
            { month: 4, expense: 30 },
            { month: 5, expense: 150 },
            { month: 6, expense: 75 },
            { month: 7, expense: 40 },
            { month: 8, expense: 90 },
            { month: 9, expense: 110 },
            { month: 10, expense: 55 },
            { month: 11, expense: 25 },
        ]
    },
    {
        year: 2007,
        "detail": [
            { month: 0, expense: 98 },
            { month: 1, expense: 23 },
            { month: 2, expense: 54 },
            { month: 3, expense: 93 },
            { month: 4, expense: 27 },
            { month: 5, expense: 64 },
            { month: 6, expense: 19 },
            { month: 7, expense: 65 },
            { month: 8, expense: 22 },
            { month: 9, expense: 89 },
            { month: 10, expense: 45 },
            { month: 11, expense: 28 },
        ]
    },
    {
        year: 2008,
        "detail": [
            { month: 0, expense: 120 },
            { month: 1, expense: 80 },
            { month: 2, expense: 45 },
            { month: 3, expense: 60 },
            { month: 4, expense: 30 },
            { month: 5, expense: 150 },
            { month: 6, expense: 75 },
            { month: 7, expense: 40 },
            { month: 8, expense: 90 },
            { month: 9, expense: 110 },
            { month: 10, expense: 55 },
            { month: 11, expense: 25 },
        ]
    },
    {
        year: 2009,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 400 },
            { month: 2, expense: 130 },
            { month: 3, expense: 55 },
            { month: 4, expense: 110 },
            { month: 5, expense: 36 },
            { month: 6, expense: 28 },
            { month: 7, expense: 92 },
            { month: 8, expense: 34 },
            { month: 9, expense: 92 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ]
    },
    {
        year: 2010,
        "detail": [
            { month: 0, expense: 70 },
            { month: 1, expense: 420 },
            { month: 2, expense: 140 },
            { month: 3, expense: 50 },
            { month: 4, expense: 105 },
            { month: 5, expense: 38 },
            { month: 6, expense: 78 },
            { month: 7, expense: 36 },
            { month: 8, expense: 82 },
            { month: 9, expense: 97 },
            { month: 10, expense: 28 },
            { month: 11, expense: 39 },
        ]
    },
    {
        year: 2011,
        "detail": [
            { month: 0, expense: 80 },
            { month: 1, expense: 120 },
            { month: 2, expense: 45 },
            { month: 3, expense: 60 },
            { month: 4, expense: 30 },
            { month: 5, expense: 150 },
            { month: 6, expense: 75 },
            { month: 7, expense: 40 },
            { month: 8, expense: 90 },
            { month: 9, expense: 110 },
            { month: 10, expense: 55 },
            { month: 11, expense: 25 },
        ]
    },
    {
        year: 2012,
        "detail": [
            { month: 0, expense: 90 },
            { month: 1, expense: 110 },
            { month: 2, expense: 35 },
            { month: 3, expense: 70 },
            { month: 4, expense: 40 },
            { month: 5, expense: 160 },
            { month: 6, expense: 65 },
            { month: 7, expense: 50 },
            { month: 8, expense: 100 },
            { month: 9, expense: 120 },
            { month: 10, expense: 45 },
            { month: 11, expense: 30 },
        ]
    },
    {
        year: 2013,
        "detail": [
            { month: 0, expense: 100 },
            { month: 1, expense: 130 },
            { month: 2, expense: 55 },
            { month: 3, expense: 80 },
            { month: 4, expense: 50 },
            { month: 5, expense: 180 },
            { month: 6, expense: 85 },
            { month: 7, expense: 60 },
            { month: 8, expense: 110 },
            { month: 9, expense: 130 },
            { month: 10, expense: 65 },
            { month: 11, expense: 40 },
        ]
    },
    {
        year: 2014,
        "detail": [
            { month: 0, expense: 120 },
            { month: 1, expense: 150 },
            { month: 2, expense: 75 },
            { month: 3, expense: 100 },
            { month: 4, expense: 70 },
            { month: 5, expense: 200 },
            { month: 6, expense: 105 },
            { month: 7, expense: 80 },
            { month: 8, expense: 130 },
            { month: 9, expense: 150 },
            { month: 10, expense: 85 },
            { month: 11, expense: 60 },
        ]
    },
    {
        year: 2015,
        "detail": [
            { month: 0, expense: 140 },
            { month: 1, expense: 170 },
            { month: 2, expense: 95 },
            { month: 3, expense: 120 },
            { month: 4, expense: 90 },
            { month: 5, expense: 220 },
            { month: 6, expense: 125 },
            { month: 7, expense: 100 },
            { month: 8, expense: 150 },
            { month: 9, expense: 170 },
            { month: 10, expense: 105 },
            { month: 11, expense: 80 },
        ]
    },
    {
        year: 2016,
        "detail": [
            { month: 0, expense: 160 },
            { month: 1, expense: 190 },
            { month: 2, expense: 115 },
            { month: 3, expense: 140 },
            { month: 4, expense: 110 },
            { month: 5, expense: 240 },
            { month: 6, expense: 145 },
            { month: 7, expense: 120 },
            { month: 8, expense: 170 },
            { month: 9, expense: 190 },
            { month: 10, expense: 125 },
            { month: 11, expense: 100 },
        ]
    },
    {
        year: 2017,
        "detail": [
            { month: 0, expense: 180 },
            { month: 1, expense: 210 },
            { month: 2, expense: 135 },
            { month: 3, expense: 160 },
            { month: 4, expense: 130 },
            { month: 5, expense: 260 },
            { month: 6, expense: 165 },
            { month: 7, expense: 140 },
            { month: 8, expense: 190 },
            { month: 9, expense: 210 },
            { month: 10, expense: 145 },
            { month: 11, expense: 120 },
        ]
    },
    {
        year: 2018,
        "detail": [
            { month: 0, expense: 200 },
            { month: 1, expense: 230 },
            { month: 2, expense: 155 },
            { month: 3, expense: 180 },
            { month: 4, expense: 150 },
            { month: 5, expense: 280 },
            { month: 6, expense: 185 },
            { month: 7, expense: 160 },
            { month: 8, expense: 210 },
            { month: 9, expense: 230 },
            { month: 10, expense: 165 },
            { month: 11, expense: 140 },
        ]
    },
    {
        year: 2019,
        "detail": [
            { month: 0, expense: 220 },
            { month: 1, expense: 250 },
            { month: 2, expense: 175 },
            { month: 3, expense: 200 },
            { month: 4, expense: 170 },
            { month: 5, expense: 300 },
            { month: 6, expense: 205 },
            { month: 7, expense: 180 },
            { month: 8, expense: 230 },
            { month: 9, expense: 250 },
            { month: 10, expense: 185 },
            { month: 11, expense: 160 },
        ]
    },
    {
        year: 2020,
        "detail": [
            { month: 0, expense: 240 },
            { month: 1, expense: 270 },
            { month: 2, expense: 195 },
            { month: 3, expense: 220 },
            { month: 4, expense: 190 },
            { month: 5, expense: 320 },
            { month: 6, expense: 225 },
            { month: 7, expense: 200 },
            { month: 8, expense: 250 },
            { month: 9, expense: 270 },
            { month: 10, expense: 205 },
            { month: 11, expense: 180 },
        ]
    },
    {
        year: 2021,
        "detail": [
            { month: 0, expense: 260 },
            { month: 1, expense: 290 },
            { month: 2, expense: 215 },
            { month: 3, expense: 240 },
            { month: 4, expense: 210 },
            { month: 5, expense: 340 },
            { month: 6, expense: 245 },
            { month: 7, expense: 220 },
            { month: 8, expense: 270 },
            { month: 9, expense: 290 },
            { month: 10, expense: 225 },
            { month: 11, expense: 200 },
        ]
    },
    {
        year: 2022,
        "detail": [
            { month: 0, expense: 280 },
            { month: 1, expense: 310 },
            { month: 2, expense: 235 },
            { month: 3, expense: 260 },
            { month: 4, expense: 230 },
            { month: 5, expense: 360 },
            { month: 6, expense: 265 },
            { month: 7, expense: 240 },
            { month: 8, expense: 290 },
            { month: 9, expense: 310 },
            { month: 10, expense: 245 },
            { month: 11, expense: 220 },
        ]
    },
    {
        year: 2023,
        "detail": [
            { month: 0, expense: 300 },
            { month: 1, expense: 330 },
            { month: 2, expense: 255 },
            { month: 3, expense: 280 },
            { month: 4, expense: 250 },
            { month: 5, expense: 380 },
            { month: 6, expense: 285 },
            { month: 7, expense: 260 },
            { month: 8, expense: 310 },
            { month: 9, expense: 330 },
            { month: 10, expense: 265 },
            { month: 11, expense: 240 },
        ]
    },
    {
        year: 2024,
        "detail": [
            { month: 0, expense: 105 },
            { month: 1, expense: 115 },
            { month: 2, expense: 125 },
            { month: 3, expense: 135 },
            { month: 4, expense: 145 },
            { month: 5, expense: 155 },
            { month: 6, expense: 165 },
            { month: 7, expense: 175 },
            { month: 8, expense: 185 },
            { month: 9, expense: 195 },
            { month: 10, expense: 205 },
            { month: 11, expense: 215 },
        ]
    },
    {
        year: 2025,
        "detail": [
            { month: 0, expense: 300 },
            { month: 1, expense: 330 },
            { month: 2, expense: 255 },
            { month: 3, expense: 280 },
            { month: 4, expense: 250 },
            { month: 5, expense: 380 },
            { month: 6, expense: 285 },
            { month: 7, expense: 260 },
            { month: 8, expense: 310 },
            { month: 9, expense: 330 },
            { month: 10, expense: 265 },
            { month: 11, expense: 240 },
        ]
    },
    {
        year: 2026,
        "detail": [
            { month: 0, expense: 105 },
            { month: 1, expense: 115 },
            { month: 2, expense: 125 },
            { month: 3, expense: 135 },
            { month: 4, expense: 145 },
            { month: 5, expense: 155 },
            { month: 6, expense: 165 },
            { month: 7, expense: 175 },
            { month: 8, expense: 185 },
            { month: 9, expense: 195 },
            { month: 10, expense: 205 },
            { month: 11, expense: 215 },
        ]
    },
    {
        year: 2027,
        "detail": [
            { month: 0, expense: 220 },
            { month: 1, expense: 250 },
            { month: 2, expense: 175 },
            { month: 3, expense: 200 },
            { month: 4, expense: 170 },
            { month: 5, expense: 300 },
            { month: 6, expense: 205 },
            { month: 7, expense: 180 },
            { month: 8, expense: 230 },
            { month: 9, expense: 250 },
            { month: 10, expense: 185 },
            { month: 11, expense: 160 },
        ]
    },
    {
        year: 2028,
        "detail": [
            { month: 0, expense: 220 },
            { month: 1, expense: 250 },
            { month: 2, expense: 175 },
            { month: 3, expense: 200 },
            { month: 4, expense: 170 },
            { month: 5, expense: 300 },
            { month: 6, expense: 205 },
            { month: 7, expense: 180 },
            { month: 8, expense: 230 },
            { month: 9, expense: 250 },
            { month: 10, expense: 185 },
            { month: 11, expense: 160 },
        ]
    },
    {
        year: 2029,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 110 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 85 },
            { month: 8, expense: 35 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 2030,
        "detail": [
            { month: 0, expense: 280 },
            { month: 1, expense: 310 },
            { month: 2, expense: 235 },
            { month: 3, expense: 260 },
            { month: 4, expense: 230 },
            { month: 5, expense: 360 },
            { month: 6, expense: 265 },
            { month: 7, expense: 240 },
            { month: 8, expense: 290 },
            { month: 9, expense: 310 },
            { month: 10, expense: 245 },
            { month: 11, expense: 220 },
        ]
    },
    {
        year: 2031,
        "detail": [
            { month: 0, expense: 280 },
            { month: 1, expense: 310 },
            { month: 2, expense: 235 },
            { month: 3, expense: 260 },
            { month: 4, expense: 230 },
            { month: 5, expense: 360 },
            { month: 6, expense: 265 },
            { month: 7, expense: 240 },
            { month: 8, expense: 290 },
            { month: 9, expense: 310 },
            { month: 10, expense: 245 },
            { month: 11, expense: 220 },
        ]
    },
    {
        year: 2032,
        "detail": [
            { month: 0, expense: 220 },
            { month: 1, expense: 250 },
            { month: 2, expense: 175 },
            { month: 3, expense: 200 },
            { month: 4, expense: 170 },
            { month: 5, expense: 300 },
            { month: 6, expense: 205 },
            { month: 7, expense: 180 },
            { month: 8, expense: 230 },
            { month: 9, expense: 250 },
            { month: 10, expense: 185 },
            { month: 11, expense: 160 },
        ]
    },
    {
        year: 2033,
        "detail": [
            { month: 0, expense: 105 },
            { month: 1, expense: 115 },
            { month: 2, expense: 125 },
            { month: 3, expense: 135 },
            { month: 4, expense: 145 },
            { month: 5, expense: 155 },
            { month: 6, expense: 165 },
            { month: 7, expense: 175 },
            { month: 8, expense: 185 },
            { month: 9, expense: 195 },
            { month: 10, expense: 205 },
            { month: 11, expense: 215 },
        ]
    },
    {
        year: 2034,
        "detail": [
            { month: 0, expense: 220 },
            { month: 1, expense: 250 },
            { month: 2, expense: 175 },
            { month: 3, expense: 200 },
            { month: 4, expense: 170 },
            { month: 5, expense: 300 },
            { month: 6, expense: 205 },
            { month: 7, expense: 180 },
            { month: 8, expense: 230 },
            { month: 9, expense: 250 },
            { month: 10, expense: 185 },
            { month: 11, expense: 160 },
        ]
    },
    {
        year: 2035,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 118 },
            { month: 3, expense: 62 },
            { month: 4, expense: 105 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 90 },
            { month: 8, expense: 32 },
            { month: 9, expense: 78 },
            { month: 10, expense: 38 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 2036,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 115 },
            { month: 3, expense: 70 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 32 },
            { month: 7, expense: 95 },
            { month: 8, expense: 38 },
            { month: 9, expense: 85 },
            { month: 10, expense: 40 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 2037,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 110 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 85 },
            { month: 8, expense: 35 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 2038,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 95 },
            { month: 2, expense: 100 },
            { month: 3, expense: 75 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 35 },
            { month: 7, expense: 90 },
            { month: 8, expense: 40 },
            { month: 9, expense: 88 },
            { month: 10, expense: 42 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 2039,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 105 },
            { month: 3, expense: 72 },
            { month: 4, expense: 115 },
            { month: 5, expense: 48 },
            { month: 6, expense: 30 },
            { month: 7, expense: 88 },
            { month: 8, expense: 38 },
            { month: 9, expense: 82 },
            { month: 10, expense: 40 },
            { month: 11, expense: 33 },
        ],
    },
    {
        year: 2040,
        "detail": [
            { month: 0, expense: 48 },
            { month: 1, expense: 78 },
            { month: 2, expense: 115 },
            { month: 3, expense: 62 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 24 },
            { month: 7, expense: 82 },
            { month: 8, expense: 28 },
            { month: 9, expense: 75 },
            { month: 10, expense: 30 },
            { month: 11, expense: 25 },
        ],
    },
    {
        year: 2041,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 85 },
            { month: 2, expense: 120 },
            { month: 3, expense: 68 },
            { month: 4, expense: 105 },
            { month: 5, expense: 42 },
            { month: 6, expense: 30 },
            { month: 7, expense: 80 },
            { month: 8, expense: 35 },
            { month: 9, expense: 78 },
            { month: 10, expense: 40 },
            { month: 11, expense: 32 },
        ],
    },
    {
        year: 2042,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 92 },
            { month: 2, expense: 110 },
            { month: 3, expense: 70 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 25 },
            { month: 7, expense: 85 },
            { month: 8, expense: 30 },
            { month: 9, expense: 82 },
            { month: 10, expense: 36 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 2043,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 118 },
            { month: 3, expense: 62 },
            { month: 4, expense: 105 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 90 },
            { month: 8, expense: 32 },
            { month: 9, expense: 78 },
            { month: 10, expense: 38 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 2044,
        "detail": [
            { month: 0, expense: 55 },
            { month: 1, expense: 88 },
            { month: 2, expense: 115 },
            { month: 3, expense: 70 },
            { month: 4, expense: 110 },
            { month: 5, expense: 45 },
            { month: 6, expense: 32 },
            { month: 7, expense: 95 },
            { month: 8, expense: 38 },
            { month: 9, expense: 85 },
            { month: 10, expense: 40 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 2045,
        "detail": [
            { month: 0, expense: 60 },
            { month: 1, expense: 92 },
            { month: 2, expense: 110 },
            { month: 3, expense: 70 },
            { month: 4, expense: 100 },
            { month: 5, expense: 38 },
            { month: 6, expense: 25 },
            { month: 7, expense: 85 },
            { month: 8, expense: 30 },
            { month: 9, expense: 82 },
            { month: 10, expense: 36 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 2046,
        "detail": [
            { month: 0, expense: 220 },
            { month: 1, expense: 250 },
            { month: 2, expense: 175 },
            { month: 3, expense: 200 },
            { month: 4, expense: 170 },
            { month: 5, expense: 300 },
            { month: 6, expense: 205 },
            { month: 7, expense: 180 },
            { month: 8, expense: 230 },
            { month: 9, expense: 250 },
            { month: 10, expense: 185 },
            { month: 11, expense: 160 },
        ]
    },
    {
        year: 2047,
        "detail": [
            { month: 0, expense: 35 },
            { month: 1, expense: 65 },
            { month: 2, expense: 100 },
            { month: 3, expense: 45 },
            { month: 4, expense: 85 },
            { month: 5, expense: 28 },
            { month: 6, expense: 15 },
            { month: 7, expense: 65 },
            { month: 8, expense: 22 },
            { month: 9, expense: 65 },
            { month: 10, expense: 25 },
            { month: 11, expense: 20 },
        ],
    },
    {
        year: 2048,
        "detail": [
            { month: 0, expense: 40 },
            { month: 1, expense: 70 },
            { month: 2, expense: 105 },
            { month: 3, expense: 50 },
            { month: 4, expense: 90 },
            { month: 5, expense: 32 },
            { month: 6, expense: 20 },
            { month: 7, expense: 70 },
            { month: 8, expense: 28 },
            { month: 9, expense: 70 },
            { month: 10, expense: 32 },
            { month: 11, expense: 28 },
        ],
    },
    {
        year: 2049,
        "detail": [
            { month: 0, expense: 45 },
            { month: 1, expense: 75 },
            { month: 2, expense: 110 },
            { month: 3, expense: 55 },
            { month: 4, expense: 95 },
            { month: 5, expense: 35 },
            { month: 6, expense: 24 },
            { month: 7, expense: 75 },
            { month: 8, expense: 30 },
            { month: 9, expense: 75 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    {
        year: 2050,
        "detail": [
            { month: 0, expense: 50 },
            { month: 1, expense: 80 },
            { month: 2, expense: 115 },
            { month: 3, expense: 60 },
            { month: 4, expense: 100 },
            { month: 5, expense: 40 },
            { month: 6, expense: 28 },
            { month: 7, expense: 80 },
            { month: 8, expense: 32 },
            { month: 9, expense: 80 },
            { month: 10, expense: 35 },
            { month: 11, expense: 30 },
        ],
    },
    // {
    //     year: 2051,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 35 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2052,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 95 },
    //         { month: 2, expense: 100 },
    //         { month: 3, expense: 75 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 45 },
    //         { month: 6, expense: 35 },
    //         { month: 7, expense: 90 },
    //         { month: 8, expense: 40 },
    //         { month: 9, expense: 88 },
    //         { month: 10, expense: 42 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2053,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 105 },
    //         { month: 3, expense: 72 },
    //         { month: 4, expense: 115 },
    //         { month: 5, expense: 48 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 88 },
    //         { month: 8, expense: 38 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 33 },
    //     ],
    // },
    // {
    //     year: 2054,
    //     "detail": [
    //         { month: 0, expense: 48 },
    //         { month: 1, expense: 78 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 62 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 24 },
    //         { month: 7, expense: 82 },
    //         { month: 8, expense: 28 },
    //         { month: 9, expense: 75 },
    //         { month: 10, expense: 30 },
    //         { month: 11, expense: 25 },
    //     ],
    // },
    // {
    //     year: 2055,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 85 },
    //         { month: 2, expense: 120 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 35 },
    //         { month: 9, expense: 78 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2056,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 92 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 70 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 25 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 30 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 36 },
    //         { month: 11, expense: 28 },
    //     ],
    // },
    // {
    //     year: 2057,
    //     "detail": [
    //         { month: 0, expense: 40 },
    //         { month: 1, expense: 70 },
    //         { month: 2, expense: 105 },
    //         { month: 3, expense: 50 },
    //         { month: 4, expense: 90 },
    //         { month: 5, expense: 32 },
    //         { month: 6, expense: 18 },
    //         { month: 7, expense: 70 },
    //         { month: 8, expense: 25 },
    //         { month: 9, expense: 70 },
    //         { month: 10, expense: 28 },
    //         { month: 11, expense: 22 },
    //     ],
    // },
    // {
    //     year: 2058,
    //     "detail": [
    //         { month: 0, expense: 45 },
    //         { month: 1, expense: 75 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 55 },
    //         { month: 4, expense: 95 },
    //         { month: 5, expense: 35 },
    //         { month: 6, expense: 24 },
    //         { month: 7, expense: 75 },
    //         { month: 8, expense: 30 },
    //         { month: 9, expense: 75 },
    //         { month: 10, expense: 32 },
    //         { month: 11, expense: 28 },
    //     ],
    // },
    // {
    //     year: 2059,
    //     "detail": [
    //         { month: 0, expense: 50 },
    //         { month: 1, expense: 80 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 60 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 40 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 32 },
    //         { month: 9, expense: 80 },
    //         { month: 10, expense: 35 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2060,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 35 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2061,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 95 },
    //         { month: 2, expense: 100 },
    //         { month: 3, expense: 75 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 45 },
    //         { month: 6, expense: 35 },
    //         { month: 7, expense: 90 },
    //         { month: 8, expense: 40 },
    //         { month: 9, expense: 88 },
    //         { month: 10, expense: 42 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2062,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 105 },
    //         { month: 3, expense: 72 },
    //         { month: 4, expense: 115 },
    //         { month: 5, expense: 48 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 88 },
    //         { month: 8, expense: 38 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 33 },
    //     ],
    // },
    // {
    //     year: 2063,
    //     "detail": [
    //         { month: 0, expense: 48 },
    //         { month: 1, expense: 78 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 62 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 24 },
    //         { month: 7, expense: 82 },
    //         { month: 8, expense: 28 },
    //         { month: 9, expense: 75 },
    //         { month: 10, expense: 30 },
    //         { month: 11, expense: 25 },
    //     ],
    // },
    // {
    //     year: 2064,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 85 },
    //         { month: 2, expense: 120 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 35 },
    //         { month: 9, expense: 78 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2065,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 92 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 70 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 25 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 30 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 36 },
    //         { month: 11, expense: 28 },
    //     ],
    // },
    // {
    //     year: 2066,
    //     "detail": [
    //         { month: 0, expense: 50 },
    //         { month: 1, expense: 80 },
    //         { month: 2, expense: 118 },
    //         { month: 3, expense: 62 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 40 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 90 },
    //         { month: 8, expense: 32 },
    //         { month: 9, expense: 78 },
    //         { month: 10, expense: 38 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2067,
    //     "detail": [
    //         { month: 0, expense: 45 },
    //         { month: 1, expense: 75 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 55 },
    //         { month: 4, expense: 95 },
    //         { month: 5, expense: 35 },
    //         { month: 6, expense: 20 },
    //         { month: 7, expense: 75 },
    //         { month: 8, expense: 28 },
    //         { month: 9, expense: 75 },
    //         { month: 10, expense: 30 },
    //         { month: 11, expense: 25 },
    //     ],
    // },
    // {
    //     year: 2068,
    //     "detail": [
    //         { month: 0, expense: 50 },
    //         { month: 1, expense: 80 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 60 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 40 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 32 },
    //         { month: 9, expense: 80 },
    //         { month: 10, expense: 35 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2069,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 35 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2030,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 95 },
    //         { month: 2, expense: 100 },
    //         { month: 3, expense: 75 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 45 },
    //         { month: 6, expense: 35 },
    //         { month: 7, expense: 90 },
    //         { month: 8, expense: 40 },
    //         { month: 9, expense: 88 },
    //         { month: 10, expense: 42 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2031,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 105 },
    //         { month: 3, expense: 72 },
    //         { month: 4, expense: 115 },
    //         { month: 5, expense: 48 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 88 },
    //         { month: 8, expense: 38 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 33 },
    //     ],
    // },
    // {
    //     year: 2032,
    //     "detail": [
    //         { month: 0, expense: 48 },
    //         { month: 1, expense: 78 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 62 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 24 },
    //         { month: 7, expense: 82 },
    //         { month: 8, expense: 28 },
    //         { month: 9, expense: 75 },
    //         { month: 10, expense: 30 },
    //         { month: 11, expense: 25 },
    //     ],
    // },
    // {
    //     year: 2033,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 85 },
    //         { month: 2, expense: 120 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 35 },
    //         { month: 9, expense: 78 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2034,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 92 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 70 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 25 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 30 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 36 },
    //         { month: 11, expense: 28 },
    //     ],
    // },
    // {
    //     year: 2036,
    //     "detail": [
    //         { month: 0, expense: 280 },
    //         { month: 1, expense: 310 },
    //         { month: 2, expense: 235 },
    //         { month: 3, expense: 260 },
    //         { month: 4, expense: 230 },
    //         { month: 5, expense: 360 },
    //         { month: 6, expense: 265 },
    //         { month: 7, expense: 240 },
    //         { month: 8, expense: 290 },
    //         { month: 9, expense: 310 },
    //         { month: 10, expense: 245 },
    //         { month: 11, expense: 220 },
    //     ]
    // },
    // {
    //     year: 2037,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 70 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 45 },
    //         { month: 6, expense: 32 },
    //         { month: 7, expense: 95 },
    //         { month: 8, expense: 38 },
    //         { month: 9, expense: 85 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2038,
    //     "detail": [
    //         { month: 0, expense: 50 },
    //         { month: 1, expense: 80 },
    //         { month: 2, expense: 120 },
    //         { month: 3, expense: 60 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 40 },
    //         { month: 6, expense: 25 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 30 },
    //         { month: 9, expense: 80 },
    //         { month: 10, expense: 32 },
    //         { month: 11, expense: 28 },
    //     ],
    // },
    // {
    //     year: 2039,
    //     "detail": [
    //         { month: 0, expense: 280 },
    //         { month: 1, expense: 310 },
    //         { month: 2, expense: 235 },
    //         { month: 3, expense: 260 },
    //         { month: 4, expense: 230 },
    //         { month: 5, expense: 360 },
    //         { month: 6, expense: 265 },
    //         { month: 7, expense: 240 },
    //         { month: 8, expense: 290 },
    //         { month: 9, expense: 310 },
    //         { month: 10, expense: 245 },
    //         { month: 11, expense: 220 },
    //     ]
    // },
    // {
    //     year: 2040,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 95 },
    //         { month: 2, expense: 100 },
    //         { month: 3, expense: 75 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 45 },
    //         { month: 6, expense: 35 },
    //         { month: 7, expense: 90 },
    //         { month: 8, expense: 40 },
    //         { month: 9, expense: 88 },
    //         { month: 10, expense: 42 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2041,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 105 },
    //         { month: 3, expense: 72 },
    //         { month: 4, expense: 115 },
    //         { month: 5, expense: 48 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 88 },
    //         { month: 8, expense: 38 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 33 },
    //     ],
    // },
    // {
    //     year: 2042,
    //     "detail": [
    //         { month: 0, expense: 58 },
    //         { month: 1, expense: 92 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 32 },
    //         { month: 9, expense: 80 },
    //         { month: 10, expense: 38 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2043,
    //     "detail": [
    //         { month: 0, expense: 48 },
    //         { month: 1, expense: 78 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 62 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 24 },
    //         { month: 7, expense: 82 },
    //         { month: 8, expense: 28 },
    //         { month: 9, expense: 75 },
    //         { month: 10, expense: 30 },
    //         { month: 11, expense: 25 },
    //     ],
    // },
    // {
    //     year: 2044,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 85 },
    //         { month: 2, expense: 120 },
    //         { month: 3, expense: 68 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 42 },
    //         { month: 6, expense: 30 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 35 },
    //         { month: 9, expense: 78 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 32 },
    //     ],
    // },
    // {
    //     year: 2045,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 92 },
    //         { month: 2, expense: 110 },
    //         { month: 3, expense: 70 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 38 },
    //         { month: 6, expense: 25 },
    //         { month: 7, expense: 85 },
    //         { month: 8, expense: 30 },
    //         { month: 9, expense: 82 },
    //         { month: 10, expense: 36 },
    //         { month: 11, expense: 28 },
    //     ],
    // },
    // {
    //     year: 2046,
    //     "detail": [
    //         { month: 0, expense: 50 },
    //         { month: 1, expense: 80 },
    //         { month: 2, expense: 118 },
    //         { month: 3, expense: 62 },
    //         { month: 4, expense: 105 },
    //         { month: 5, expense: 40 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 90 },
    //         { month: 8, expense: 32 },
    //         { month: 9, expense: 78 },
    //         { month: 10, expense: 38 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2047,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 88 },
    //         { month: 2, expense: 115 },
    //         { month: 3, expense: 70 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 45 },
    //         { month: 6, expense: 32 },
    //         { month: 7, expense: 95 },
    //         { month: 8, expense: 38 },
    //         { month: 9, expense: 85 },
    //         { month: 10, expense: 40 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2048,
    //     "detail": [
    //         { month: 0, expense: 50 },
    //         { month: 1, expense: 380 },
    //         { month: 2, expense: 120 },
    //         { month: 3, expense: 60 },
    //         { month: 4, expense: 100 },
    //         { month: 5, expense: 40 },
    //         { month: 6, expense: 25 },
    //         { month: 7, expense: 80 },
    //         { month: 8, expense: 30 },
    //         { month: 9, expense: 80 },
    //         { month: 10, expense: 32 },
    //         { month: 11, expense: 28 },
    //     ],
    // },
    // {
    //     year: 2049,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 400 },
    //         { month: 2, expense: 130 },
    //         { month: 3, expense: 65 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 36 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 92 },
    //         { month: 8, expense: 34 },
    //         { month: 9, expense: 92 },
    //         { month: 10, expense: 35 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2050,
    //     "detail": [
    //         { month: 0, expense: 40 },
    //         { month: 1, expense: 67 },
    //         { month: 2, expense: 89 },
    //         { month: 3, expense: 23 },
    //         { month: 4, expense: 54 },
    //         { month: 5, expense: 72 },
    //         { month: 6, expense: 38 },
    //         { month: 7, expense: 19 },
    //         { month: 8, expense: 22 },
    //         { month: 9, expense: 11 },
    //         { month: 10, expense: 36 },
    //         { month: 11, expense: 98 },
    //     ],
    // },
    // {
    //     year: 2051,
    //     "detail": [
    //         { month: 0, expense: 55 },
    //         { month: 1, expense: 400 },
    //         { month: 2, expense: 130 },
    //         { month: 3, expense: 65 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 36 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 92 },
    //         { month: 8, expense: 34 },
    //         { month: 9, expense: 92 },
    //         { month: 10, expense: 35 },
    //         { month: 11, expense: 30 },
    //     ],
    // },
    // {
    //     year: 2052,
    //     "detail": [
    //         { month: 0, expense: 280 },
    //         { month: 1, expense: 310 },
    //         { month: 2, expense: 235 },
    //         { month: 3, expense: 260 },
    //         { month: 4, expense: 230 },
    //         { month: 5, expense: 360 },
    //         { month: 6, expense: 265 },
    //         { month: 7, expense: 240 },
    //         { month: 8, expense: 290 },
    //         { month: 9, expense: 310 },
    //         { month: 10, expense: 245 },
    //         { month: 11, expense: 220 },
    //     ]
    // },
    // {
    //     year: 2053,
    //     "detail": [
    //         { month: 0, expense: 280 },
    //         { month: 1, expense: 310 },
    //         { month: 2, expense: 235 },
    //         { month: 3, expense: 260 },
    //         { month: 4, expense: 230 },
    //         { month: 5, expense: 360 },
    //         { month: 6, expense: 265 },
    //         { month: 7, expense: 240 },
    //         { month: 8, expense: 290 },
    //         { month: 9, expense: 310 },
    //         { month: 10, expense: 245 },
    //         { month: 11, expense: 220 },
    //     ]
    // },
    // {
    //     year: 2054,
    //     "detail": [
    //         { month: 0, expense: 60 },
    //         { month: 1, expense: 400 },
    //         { month: 2, expense: 130 },
    //         { month: 3, expense: 55 },
    //         { month: 4, expense: 110 },
    //         { month: 5, expense: 36 },
    //         { month: 6, expense: 28 },
    //         { month: 7, expense: 92 },
    //         { month: 8, expense: 34 },
    //         { month: 9, expense: 92 },
    //         { month: 10, expense: 35 },
    //         { month: 11, expense: 30 },
    //     ]
    // },
    // {
    //     year: 2055,
    //     "detail": [
    //         { month: 0, expense: 280 },
    //         { month: 1, expense: 310 },
    //         { month: 2, expense: 235 },
    //         { month: 3, expense: 260 },
    //         { month: 4, expense: 230 },
    //         { month: 5, expense: 360 },
    //         { month: 6, expense: 265 },
    //         { month: 7, expense: 240 },
    //         { month: 8, expense: 290 },
    //         { month: 9, expense: 310 },
    //         { month: 10, expense: 245 },
    //         { month: 11, expense: 220 },
    //     ]
    // },
];

// Calculate age by birthday
export function calculateAge(birthday) {

    const today = new Date();
    const birth = new Date(birthday);

    const age = today.getFullYear() - birth.getFullYear();
    const monthDiff = today.getMonth() - birth.getMonth();

    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
        age--;
    }

    return age;
}

// Calculate total expense by year
export function calculateTotalExpensesByYear(data, selectedYear) {
    const yearData = data.find(item => item.year === selectedYear);

    if (!yearData) {
        console.log(`Không tìm thấy dữ liệu của năm ${selectedYear}`);
        return null;
    }
    const totalExpenseForYear = yearData.detail.reduce((sum, month) => sum + month.expense, 0);

    return totalExpenseForYear;
}


// Generate event expense by year
export function generateEventsByYear(data, age) {
    const events = [];

    const currentYear = new Date().getFullYear();
    const targetAge = 100;
    const endYear = currentYear + (targetAge - age);

    for (let i = 0; i < endYear; i++) {
        const iYear = currentYear + i;

        const yearData = data.find(item => item.year === iYear);

        if (yearData) {
            const totalExpenseForYear = yearData.detail.reduce((sum, month) => sum + month.expense, 0);
            const event = { year: iYear, totalExpense: totalExpenseForYear };
            events.push(event);
        } else {
            console.log(`Không tìm thấy dữ liệu của năm ${iYear}`);
        }
    }

    return events;
}

// Generate event expense by month (1-12 months) [startYear; endYear]
export function generateEventsByMonth(data, startYear, endYear) {
    const events = Array.from({ length: 12 }, () => ({ totalExpense: 0 }));

    for (let year = startYear; year <= endYear; year++) {
        const yearData = data.find(item => item.year === year);

        if (yearData) {
            yearData.detail.forEach(month => {
                const monthIndex = month.month;
                events[monthIndex].totalExpense += month.expense;
            });
        } else {
            console.log(`Không tìm thấy dữ liệu của năm ${year}`);
        }
    }

    return events.map((total, index) => ({ month: index, ...total }));
}