export const generateEvents = (minAge, maxAge) => {
    const events = [
        // ... (events array)
        { age: 1, icon: 'birthday-cake', description: 'First Birthday', expense: 10 },
        { age: 2, icon: 'baby', description: 'Learning to Walk', expense: 30 },
        { age: 3, icon: 'play', description: 'Exploring Playtime', expense: 20 },
        { age: 4, icon: 'building-blocks', description: 'Building with Blocks', expense: 15 },
        { age: 5, icon: 'school', description: 'Start School', expense: 100 },
        { age: 6, icon: 'friendship', description: 'Making Friends', expense: 25 },
        { age: 7, icon: 'book', description: 'Learn to Read', expense: 20 },
        { age: 8, icon: 'science', description: 'Discovering Science', expense: 30 },
        { age: 9, icon: 'sports', description: 'Sports Enthusiast', expense: 40 },
        { age: 10, icon: 'graduation-cap', description: 'Elementary School Graduation', expense: 60 },
        { age: 11, icon: 'technology', description: 'Tech Explorer', expense: 50 },
        { age: 12, icon: 'arts-crafts', description: 'Arts and Crafts', expense: 35 },
        { age: 13, icon: 'trophy', description: 'Teen Achievements', expense: 70 },
        { age: 14, icon: 'music', description: 'Musical Tastes', expense: 45 },
        { age: 15, icon: 'friends', description: 'Friendship Bonds', expense: 30 },
        { age: 16, icon: 'car', description: 'Driver\'s License', expense: 80 },
        { age: 17, icon: 'party', description: 'Party Time', expense: 55 },
        { age: 18, icon: 'id-card', description: 'Legal Adult', expense: 60 },
        { age: 19, icon: 'career', description: 'Career Aspirations', expense: 65 },
        { age: 20, icon: 'technology', description: 'Digital Era', expense: 70 },
        { age: 21, icon: 'glass-cheers', description: 'Legal Drinking Age', expense: 40 },
        { age: 22, icon: 'glass-cheers', description: 'Legal Drinking Age', expense: 80 },
        { age: 23, icon: 'fitness', description: 'Fitness Journey', expense: 45 },
        { age: 24, icon: 'travel', description: 'Adventurous Spirit', expense: 75 },
        { age: 25, icon: 'airplane', description: 'Travel', expense: 70 },
        { age: 26, icon: 'ring', description: 'Engagement', expense: 80 },
        { age: 27, icon: 'wedding', description: 'Wedding', expense: 90 },
        { age: 28, icon: 'career', description: 'Career Advancements', expense: 60 },
        { age: 29, icon: 'hobby', description: 'New Hobbies', expense: 55 },
        { age: 30, icon: 'home', description: 'Home Purchase', expense: 200 },
        { age: 31, icon: 'garden', description: 'Gardening Enthusiast', expense: 65 },
        { age: 32, icon: 'foodie', description: 'Foodie Adventures', expense: 70 },
        { age: 33, icon: 'learning', description: 'Lifelong Learning', expense: 75 },
        { age: 34, icon: 'community', description: 'Community Engagement', expense: 80 },
        { age: 35, icon: 'globe', description: 'International Travel', expense: 120 },
        { age: 36, icon: 'pets', description: 'Pet Parenthood', expense: 85 },
        { age: 37, icon: 'family', description: 'Family Milestones', expense: 90 },
        { age: 38, icon: 'fitness', description: 'Healthy Lifestyle', expense: 95 },
        { age: 39, icon: 'hiking', description: 'Hiking Adventures', expense: 100 },
        { age: 40, icon: 'family', description: 'Growing Family', expense: 110 },
        { age: 41, icon: 'arts-crafts', description: 'Creative Pursuits', expense: 65 },
        { age: 42, icon: 'technology', description: 'Tech Savvy', expense: 70 },
        { age: 43, icon: 'music', description: 'Musical Journey', expense: 75 },
        { age: 44, icon: 'celebration', description: 'Celebration Time', expense: 80 },
        { age: 45, icon: 'retirement', description: 'Retirement', expense: 100 },
        { age: 46, icon: 'travel-bag', description: 'Wanderlust', expense: 85 },
        { age: 47, icon: 'volunteer', description: 'Giving Back', expense: 90 },
        { age: 48, icon: 'hobby', description: 'Creative Hobbies', expense: 95 },
        { age: 49, icon: 'gourmet', description: 'Gourmet Cooking', expense: 100 },
        { age: 50, icon: 'travel-bag', description: 'Bucket List Adventures', expense: 90 },
        { age: 51, icon: 'music', description: 'Music Appreciation', expense: 95 },
        { age: 52, icon: 'fitness', description: 'Fitness Goals', expense: 100 },
        { age: 53, icon: 'hiking', description: 'Nature Retreats', expense: 105 },
        { age: 54, icon: 'arts-crafts', description: 'Artistic Pursuits', expense: 110 },
        { age: 55, icon: 'grandparent', description: 'Becoming a Grandparent', expense: 70 },
        { age: 56, icon: 'travel', description: 'Traveling the World', expense: 115 },
        { age: 57, icon: 'technology', description: 'Embracing Technology', expense: 120 },
        { age: 58, icon: 'hobby', description: 'New Hobbies', expense: 125 },
        { age: 59, icon: 'gourmet', description: 'Culinary Delights', expense: 130 },
        { age: 60, icon: 'gold-watch', description: 'Golden Years', expense: 80 },
        { age: 61, icon: 'travel', description: 'Retirement Travel', expense: 120 },
        { age: 62, icon: 'pension', description: 'Social Security Benefits', expense: 80 },
        { age: 63, icon: 'health', description: 'Health and Wellness', expense: 100 },
        { age: 64, icon: 'hobby', description: 'Pursuing Hobbies', expense: 60 },
        { age: 65, icon: 'legacy', description: 'Creating a Legacy', expense: 150 },
        { age: 66, icon: 'relaxation', description: 'Relaxation and Leisure', expense: 90 },
        { age: 67, icon: 'family-reunion', description: 'Family Reunion', expense: 120 },
        { age: 68, icon: 'achievement', description: 'Lifetime Achievements', expense: 100 },
        { age: 69, icon: 'centenarian', description: 'Approaching 70', expense: 200 },
        { age: 70, icon: 'travel', description: 'Celebrating 70 Years', expense: 120 },
        { age: 71, icon: 'wisdom', description: 'Gaining Wisdom', expense: 80 },
        { age: 72, icon: 'hobby', description: 'Exploring New Hobbies', expense: 70 },
        { age: 73, icon: 'volunteer', description: 'Volunteering', expense: 50 },
        { age: 74, icon: 'hiking', description: 'Hiking Adventures', expense: 90 },
        { age: 75, icon: 'family', description: 'Quality Family Time', expense: 100 },
        { age: 76, icon: 'learning', description: 'Continued Learning', expense: 60 },
        { age: 77, icon: 'art', description: 'Artistic Pursuits', expense: 70 },
        { age: 78, icon: 'book', description: 'Book Club', expense: 40 },
        { age: 79, icon: 'garden', description: 'Gardening', expense: 50 },
        { age: 80, icon: 'travel', description: 'Traveling the World', expense: 120 },
        { age: 81, icon: 'music', description: 'Musical Journey', expense: 80 },
        { age: 82, icon: 'fitness', description: 'Fitness Routine', expense: 70 },
        { age: 83, icon: 'gourmet', description: 'Gourmet Cooking', expense: 90 },
        { age: 84, icon: 'pets', description: 'Pet Companionship', expense: 60 },
        { age: 85, icon: 'relaxation', description: 'Relaxation and Leisure', expense: 100 },
        { age: 86, icon: 'community', description: 'Community Involvement', expense: 50 },
        { age: 87, icon: 'technology', description: 'Embracing Technology', expense: 80 },
        { age: 88, icon: 'celebration', description: 'Celebrating Life', expense: 150 },
        { age: 89, icon: 'learning', description: 'Learning New Skills', expense: 70 },
        { age: 90, icon: 'family-reunion', description: 'Grand Family Reunion', expense: 120 },
        { age: 91, icon: 'adventure', description: 'Adventure Seeker', expense: 100 },
        { age: 92, icon: 'golf', description: 'Golfing Retreats', expense: 90 },
        { age: 93, icon: 'art', description: 'Art Appreciation', expense: 60 },
        { age: 94, icon: 'gourmet', description: 'Culinary Delights', expense: 80 },
        { age: 95, icon: 'legacy', description: 'Building a Lasting Legacy', expense: 150 },
        { age: 96, icon: 'travel-bag', description: 'Adventure Awaits', expense: 120 },
        { age: 97, icon: 'volunteer', description: 'Giving Back', expense: 50 },
        { age: 98, icon: 'wisdom', description: 'Wise Reflections', expense: 80 },
        { age: 99, icon: 'milestone', description: '99 and Counting', expense: 200 },
        { age: 100, icon: 'centenarian', description: 'Centenarian Celebration', expense: 300 },
    ];

    const filteredEvents = events.filter(event => event.age >= minAge && event.age <= maxAge);

    return filteredEvents.map(event => ({
        ...event,
        expense: event.expense || 0,
    }));
};